import { randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
import { withTransaction } from '../../database/transaction.js';
import { recordAiDiscoveryRunInTransaction } from '../ai-discovery/record-ai-discovery-run.js';
import type { RecordAiDiscoveryRunCommand,RecordAiDiscoveryRunResult } from '../ai-discovery/types.js';
import { deterministicAiProviderClientRequestId } from './client-request-id.js';
import type { AiProviderAttemptDisposition,AiProviderAttemptOrdinal } from './types.js';
export interface FinalizeAiProviderExecutionCommand{executionId:string;attemptId:string;ordinal:AiProviderAttemptOrdinal;disposition:AiProviderAttemptDisposition;completedRun?:RecordAiDiscoveryRunCommand|undefined;failedRun?:RecordAiDiscoveryRunCommand|undefined;}
export type FinalizeAiProviderExecutionResult={kind:'COMPLETED';run:RecordAiDiscoveryRunResult}|{kind:'FAILED';run:RecordAiDiscoveryRunResult}|{kind:'RETRY_PREPARED';attemptId:string;ordinal:AiProviderAttemptOrdinal;clientRequestId:string}|{kind:'UNCERTAIN'};
export async function finalizeAiProviderExecution(pool:Pool,command:FinalizeAiProviderExecutionCommand):Promise<FinalizeAiProviderExecutionResult>{return withTransaction(pool,async client=>{const locked=await client.query<{status:string;current_attempt_ordinal:number;lease_token:string|null;lease_expires_at:Date|string|null}>(`select status,current_attempt_ordinal,lease_token,lease_expires_at from ai_provider_executions where ai_provider_execution_id=$1 for update`,[command.executionId]);const execution=locked.rows[0];if(!execution||execution.status!=='IN_FLIGHT'||execution.current_attempt_ordinal!==command.ordinal)throw new Error('AI_PROVIDER_EXECUTION_FINALIZATION_CONFLICT');const providerRequestId=command.disposition.kind==='COMPLETED'?command.disposition.result.providerRequestId:command.disposition.providerRequestId;
if(command.disposition.kind==='COMPLETED'){if(!command.completedRun)throw new Error('AI_PROVIDER_EXECUTION_FINALIZATION_INPUT_INVALID');const run=await recordAiDiscoveryRunInTransaction(client,command.completedRun);await client.query(`update ai_provider_execution_attempts set status='COMPLETED',provider_request_id=$3,provider_response_id=$4,output_hash=$5,completed_at=clock_timestamp() where ai_provider_execution_attempt_id=$1 and ai_provider_execution_id=$2 and status='IN_FLIGHT'`,[command.attemptId,command.executionId,command.disposition.result.providerRequestId,command.disposition.result.providerResponseId??null,command.completedRun.outputHash]);await client.query(`update ai_provider_executions set status='COMPLETED',lease_token=null,leased_at=null,lease_expires_at=null,terminal_at=clock_timestamp(),updated_at=clock_timestamp() where ai_provider_execution_id=$1`,[command.executionId]);return{kind:'COMPLETED',run};}
if(command.disposition.kind==='SAFE_TERMINAL'){if(!command.failedRun)throw new Error('AI_PROVIDER_EXECUTION_FINALIZATION_INPUT_INVALID');const run=await recordAiDiscoveryRunInTransaction(client,command.failedRun);await client.query(`update ai_provider_execution_attempts set status='FAILED',failure_code=$3,provider_request_id=$4,completed_at=clock_timestamp() where ai_provider_execution_attempt_id=$1 and ai_provider_execution_id=$2 and status='IN_FLIGHT'`,[command.attemptId,command.executionId,command.disposition.failureCode,providerRequestId]);await client.query(`update ai_provider_executions set status='FAILED',lease_token=null,leased_at=null,lease_expires_at=null,terminal_at=clock_timestamp(),updated_at=clock_timestamp() where ai_provider_execution_id=$1`,[command.executionId]);return{kind:'FAILED',run};}
if(command.disposition.kind==='SAFE_RETRYABLE'){await client.query(`update ai_provider_execution_attempts set status='FAILED',failure_code=$3,provider_request_id=$4,completed_at=clock_timestamp() where ai_provider_execution_attempt_id=$1 and ai_provider_execution_id=$2 and status='IN_FLIGHT'`,[command.attemptId,command.executionId,command.disposition.failureCode,providerRequestId]);if(command.ordinal===3){if(!command.failedRun)throw new Error('AI_PROVIDER_EXECUTION_FINALIZATION_INPUT_INVALID');const run=await recordAiDiscoveryRunInTransaction(client,command.failedRun);await client.query(`update ai_provider_executions set status='FAILED',lease_token=null,leased_at=null,lease_expires_at=null,terminal_at=clock_timestamp(),updated_at=clock_timestamp() where ai_provider_execution_id=$1`,[command.executionId]);return{kind:'FAILED',run};}const nextOrdinal=(command.ordinal+1) as AiProviderAttemptOrdinal,nextAttemptId=randomUUID(),clientRequestId=deterministicAiProviderClientRequestId(command.executionId,nextOrdinal);await client.query(`insert into ai_provider_execution_attempts(ai_provider_execution_attempt_id,ai_provider_execution_id,ordinal,client_request_id,status) values($1,$2,$3,$4,'PREPARED')`,[nextAttemptId,command.executionId,nextOrdinal,clientRequestId]);await client.query(`update ai_provider_executions set status='PREPARED',current_attempt_ordinal=$2,lease_token=case when lease_expires_at>clock_timestamp() then lease_token else null end,leased_at=case when lease_expires_at>clock_timestamp() then leased_at else null end,lease_expires_at=case when lease_expires_at>clock_timestamp() then lease_expires_at else null end,updated_at=clock_timestamp() where ai_provider_execution_id=$1`,[command.executionId,nextOrdinal]);return{kind:'RETRY_PREPARED',attemptId:nextAttemptId,ordinal:nextOrdinal,clientRequestId};}
await client.query(`update ai_provider_execution_attempts set status='UNCERTAIN',failure_code=$3,provider_request_id=$4,completed_at=clock_timestamp() where ai_provider_execution_attempt_id=$1 and ai_provider_execution_id=$2 and status='IN_FLIGHT'`,[command.attemptId,command.executionId,command.disposition.failureCode,providerRequestId]);await client.query(`update ai_provider_executions set status='UNCERTAIN',lease_token=null,leased_at=null,lease_expires_at=null,updated_at=clock_timestamp() where ai_provider_execution_id=$1`,[command.executionId]);return{kind:'UNCERTAIN'};});}
