import type { AiProviderRequest } from './build-provider-request.js';

const DEFAULT_OPENAI_RESPONSES_ENDPOINT='https://api.openai.com/v1/responses';
const DEFAULT_TIMEOUT_MS=30_000,MIN_TIMEOUT_MS=1_000,MAX_TIMEOUT_MS=60_000,MAX_IDENTIFIER_LENGTH=128,MAX_RATIONALE_LENGTH=2_000,MAX_PROPOSALS=64,MAX_SELECTION_IDS=128,MAX_OUTPUT_TEXT_BYTES=256*1024;
const PRINTABLE_IDENTIFIER_PATTERN=/^[!-~]+$/u;
export interface AiProviderProposal{subjectExternalId:string;augmentExternalIds:string[];itemExternalIds:string[];rationale:string|null;}
export interface AiProviderResult{providerRequestId:string|null;providerResponseId?:string|null;outputText:string;proposals:AiProviderProposal[];}
export interface AiProviderExecuteOptions{clientRequestId:string;}
export interface AiDiscoveryProvider{readonly providerKey:string;execute(request:AiProviderRequest,options?:AiProviderExecuteOptions):Promise<AiProviderResult>;}
export class AiProviderError extends Error{constructor(public readonly code:string,public readonly retryable:boolean,public readonly failureCode:string,public readonly providerRequestId:string|null=null){super(code);this.name='AiProviderError';}}
export interface OpenAiResponsesProviderConfig{apiKey:string;model:string;endpoint?:string;timeoutMs?:number;fetchImpl?:typeof fetch;}
function isRecord(v:unknown):v is Record<string,unknown>{return v!==null&&typeof v==='object'&&!Array.isArray(v);}
function hasExactKeys(r:Record<string,unknown>,e:readonly string[]):boolean{const k=Object.keys(r).sort(),x=[...e].sort();return k.length===x.length&&k.every((v,i)=>v===x[i]);}
function failOutput(req:string|null=null):never{throw new AiProviderError('AI_PROVIDER_OUTPUT_INVALID',false,'PROVIDER_RESPONSE_INVALID',req);}
function failAllowlist(req:string|null=null):never{throw new AiProviderError('AI_PROVIDER_ALLOWLIST_VIOLATION',false,'PROVIDER_RESPONSE_INVALID',req);}
function failConfig():never{throw new AiProviderError('AI_PROVIDER_CONFIG_INVALID',false,'PROVIDER_REQUEST_REJECTED');}
function requireIdentifier(v:unknown):string{if(typeof v!=='string'||v.length===0||v.length>MAX_IDENTIFIER_LENGTH||v!==v.trim()||!PRINTABLE_IDENTIFIER_PATTERN.test(v))return failOutput();return v;}
function compareAscii(a:string,b:string):number{return a<b?-1:a>b?1:0;}
function requireSelectionIds(v:unknown):string[]{if(!Array.isArray(v)||v.length>MAX_SELECTION_IDS)return failOutput();const ids=v.map(requireIdentifier);if(new Set(ids).size!==ids.length)return failOutput();return ids.sort(compareAscii);}
function requireRationale(v:unknown):string|null{if(v===null)return null;if(typeof v!=='string'||v.length>MAX_RATIONALE_LENGTH)return failOutput();return v;}
function validateStructuredOutput(v:unknown,request:AiProviderRequest,req:string|null):AiProviderProposal[]{if(!isRecord(v)||!hasExactKeys(v,['proposals'])||!Array.isArray(v.proposals)||v.proposals.length>MAX_PROPOSALS)return failOutput(req);const valid=v.proposals.map((p):AiProviderProposal=>{if(!isRecord(p)||!hasExactKeys(p,['augmentExternalIds','itemExternalIds','rationale','subjectExternalId']))return failOutput(req);return{subjectExternalId:requireIdentifier(p.subjectExternalId),augmentExternalIds:requireSelectionIds(p.augmentExternalIds),itemExternalIds:requireSelectionIds(p.itemExternalIds),rationale:requireRationale(p.rationale)};});const subjects=new Map(request.input.subjects.map(s=>[s.subjectExternalId,s] as const));for(const p of valid){const s=subjects.get(p.subjectExternalId);if(!s)return failAllowlist(req);const a=new Set(s.allowedAugmentExternalIds),i=new Set(s.allowedItemExternalIds);if(p.augmentExternalIds.some(x=>!a.has(x))||p.itemExternalIds.some(x=>!i.has(x)))return failAllowlist(req);}return valid;}
function safeHeader(v:string|null):string|null{return v!==null&&v.length>0&&v.length<=256&&/^[\x20-\x7e]+$/u.test(v)?v:null;}
function safeHttpError(status:number,req:string|null):AiProviderError{if(status===401||status===403)return new AiProviderError('PROVIDER_AUTH_REJECTED',false,'PROVIDER_AUTH_REJECTED',req);if(status===408)return new AiProviderError('PROVIDER_TIMEOUT',true,'PROVIDER_TIMEOUT',req);if(status===429)return new AiProviderError('PROVIDER_RATE_LIMITED',true,'PROVIDER_RATE_LIMITED',req);if(status>=500&&status<=599)return new AiProviderError('PROVIDER_UNAVAILABLE',true,'PROVIDER_UNAVAILABLE',req);return new AiProviderError('PROVIDER_REQUEST_REJECTED',false,'PROVIDER_REQUEST_REJECTED',req);}
function extractOutputText(v:unknown,req:string|null):{providerResponseId:string|null;outputText:string}{if(!isRecord(v)||v.status!=='completed'||!Array.isArray(v.output))return failOutput(req);const texts:string[]=[];for(const item of v.output){if(!isRecord(item)||item.type!=='message'||!Array.isArray(item.content))continue;for(const c of item.content){if(isRecord(c)&&c.type==='output_text'&&typeof c.text==='string')texts.push(c.text);}}if(texts.length!==1)return failOutput(req);const outputText=texts[0]!;if(Buffer.byteLength(outputText,'utf8')>MAX_OUTPUT_TEXT_BYTES)return failOutput(req);return{providerResponseId:typeof v.id==='string'&&v.id.length>0&&v.id.length<=256?v.id:null,outputText};}
function validateConfig(c:OpenAiResponsesProviderConfig):Required<Pick<OpenAiResponsesProviderConfig,'apiKey'|'model'|'endpoint'|'timeoutMs'|'fetchImpl'>>{if(typeof c.apiKey!=='string'||c.apiKey.length===0||typeof c.model!=='string'||c.model.length===0||c.model.length>MAX_IDENTIFIER_LENGTH||c.model!==c.model.trim())return failConfig();const endpoint=c.endpoint??DEFAULT_OPENAI_RESPONSES_ENDPOINT;try{new URL(endpoint);}catch{return failConfig();}const timeoutMs=c.timeoutMs??DEFAULT_TIMEOUT_MS;if(!Number.isSafeInteger(timeoutMs)||timeoutMs<MIN_TIMEOUT_MS||timeoutMs>MAX_TIMEOUT_MS)return failConfig();return{apiKey:c.apiKey,model:c.model,endpoint,timeoutMs,fetchImpl:c.fetchImpl??fetch};}
function validateClientRequestId(v:string):string{if(v.length===0||v.length>512||!/^[\x20-\x7e]+$/u.test(v))throw new AiProviderError('AI_PROVIDER_CLIENT_REQUEST_ID_INVALID',false,'PROVIDER_REQUEST_REJECTED');return v;}
export function createOpenAiResponsesProvider(config:OpenAiResponsesProviderConfig):AiDiscoveryProvider{const c=validateConfig(config);return{providerKey:'openai',async execute(request,options){let response:Response;const client=options?.clientRequestId===undefined?null:validateClientRequestId(options.clientRequestId);try{const headers:Record<string,string>={Authorization:`Bearer ${c.apiKey}`,'Content-Type':'application/json'};if(client!==null)headers['X-Client-Request-Id']=client;response=await c.fetchImpl(c.endpoint,{method:'POST',headers,body:JSON.stringify({model:c.model,input:request.messages,store:false,text:{format:{type:'json_schema',name:'aram_mayhem_discovery',strict:true,schema:request.responseSchema}}}),signal:AbortSignal.timeout(c.timeoutMs)});}catch(error){if(error instanceof AiProviderError)throw error;if(error instanceof Error&&(error.name==='AbortError'||error.name==='TimeoutError'))throw new AiProviderError('PROVIDER_TIMEOUT',true,'PROVIDER_TIMEOUT');throw new AiProviderError('PROVIDER_TRANSPORT_ERROR',true,'PROVIDER_TRANSPORT_ERROR');}const providerRequestId=safeHeader(response.headers.get('x-request-id'));if(!response.ok)throw safeHttpError(response.status,providerRequestId);let body:unknown;try{body=await response.json();}catch{return failOutput(providerRequestId);}const{providerResponseId,outputText}=extractOutputText(body,providerRequestId);let structured:unknown;try{structured=JSON.parse(outputText);}catch{return failOutput(providerRequestId);}return{providerRequestId,providerResponseId,outputText,proposals:validateStructuredOutput(structured,request,providerRequestId)};}};}
